export * from './about'
export * from './contacts'
export * from './education'
export * from './experience'
export * from './feedback'
export * from './hard-skills'
export * from './home'
// export * from './not-found'
export * from './portfolio'
